name: Fly Deploy
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual trigger"
        required: true

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "ed25519"
          fileDir: ".ssh"
          encodedString: ${{ secrets.SSH_KEY }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
