name: Fly Deploy
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual trigger"
        required: true

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: create ssh key file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "id_ed25519"
          fileDir: ".ssh"
          encodedString: ${{ secrets.SSH_KEY }}

      - name: create env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SMTP_AUTH_IDENTITY: ${{ secrets.SMTP_AUTH_IDENTITY }}
          envkey_SMTP_AUTH_USERNAME: ${{ secrets.SMTP_AUTH_USERNAME }}
          envkey_SMTP_AUTH_PASSWORD: ${{ secrets.SMTP_AUTH_PASSWORD }}
          envkey_SMTP_AUTH_HOST: ${{ secrets.SMTP_AUTH_HOST }}
          envkey_SMTP_SEND_ADDR: ${{ secrets.SMTP_SEND_ADDR }}
          envkey_MAIL_RECIPIENT: ${{ secrets.MAIL_RECIPIENT }}
          file_name: .env

      - name: setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: deploy to fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
